swagger: '2.0'

info:
  version: "0.0.1"
  title: Bank Customers

consumes:
  - text/plain

produces:
  - application/json

paths:
  /customers:
    get:
      tags:
        - customers
      operationId: getAll
      description: Get all customers
      responses:
        200:
          $ref: '#/responses/getAllCustomers'
    post:
      tags:
        - customers
      operationId: add
      description: Add new Customer
      parameters:
        - $ref: '#/parameters/CustomerNameParam'
      responses:
        200:
          $ref: '#/responses/getOneCustomer'

  /customer/{id}:
    get:
      tags:
        - customers
      operationId: get
      description: Get customer by ID
      parameters:
        - $ref: '#/parameters/idParam'
      responses:
        200:
          $ref: '#/responses/getOneCustomer'



    delete:
      tags:
        - customers
      operationId: delete
      description: Delete customer by ID
      parameters:
        - $ref: '#/parameters/idParam'
      responses:
        200:
          $ref: '#/responses/getOneCustomer'


  /customer/{id}/goals:
    get:
      tags:
        - goals
      operationId: get
      description: Get goals using customer ID
      parameters:
        - $ref: '#/parameters/idParam'
      responses:
        200:
          $ref: '#/responses/getGoalsCustomer'

    post:
      tags:
        - goals
      operationId: add
      description: Add new Goal using customer id
      parameters:
        - $ref: '#/parameters/getGoalsCustomer'
      responses:
        200:
          $ref: '#/responses/getGoalsCustomer'



definitions:

  goal:
    type: object
    description: A goal object
    required:
      - value
      - name
      - date
      - priority
      - accountid

    properties:
      value:
        type: integer
      saved:
        type: integer
      name:
        type: string
      date:
        type: string
      priority:
        type: integer
      accountid:
        type: string

  customer:
    type: object
    description: A customer object
    required:
      - _id
      - _rev
      - birth
      - registrationdate
      - expectedincome
    properties:
      _id:
        type: integer
        format: int64
      _rev:
        type: integer
        format: int64
      birth:
        type: string
      registrationdate:
        type: string
      expectedincome:
        type: integer
      goals:
        type: array
        items:
          $ref: '#/definitions/goal'


responses:
  getOneCustomer:
    description: One customer
    schema:
      $ref: '#/definitions/customer'

  getAllCustomers:
    description: List of all customers
    schema:
      type: array
      items:
        $ref: '#/definitions/customer'

  getGoalsCustomer:
    description: Get the goals of one customer
    schema:
      type: array
      $ref: '#/definitions/goal'

parameters:
  idParam:
    name: id
    in: path
    description: Customer ID
    required: true
    type: integer
    format: int64
